Added aggregated report endpoint
fabieu/sureflap-api pull request #28
Opened 2024-04-24 22:24 UTC by EdwardSalter

Added an endpoint to fetch the aggregated report which matches the endpoint that the official Sure PetCare application uses to provide a history of events for a given pet.

2024-04-25 15:51 UTC, fabieu commented
Hey @EdwardSalter, thank you for your contribution. I added some feedback and looking forward to an answer.

2024-04-26 10:16 UTC, EdwardSalter commented
> Hey @EdwardSalter, thank you for your contribution. I added some feedback and looking forward to an answer.

Hi @fabieu , I'm probably being a bit dense but I cannot see any further comments or feedback. Are you able to point out where it is?

2024-04-26 19:07 UTC, fabieu requested changes

2024-04-26 19:07 UTC, fabieu commented on sureflap_api/main.py
> +@app.get('/report/household/{household_id}/pet/{pet_id}', response_model=response_models.AggregatedReport, tags=["Report"])
We should preferably use `/household/{household_id}/pet/{pet_id}/report` as the endpoint since the report ist based on a pet inside a household.

2024-04-26 19:07 UTC, fabieu commented on sureflap_api/models/response.py
> +    from_: datetime = Field(alias="from")
Whats the reason for using `from_` as the attribute name instead of `from`?

2024-04-26 19:07 UTC, fabieu commented on sureflap_api/main.py
> +@app.get('/report/household/{household_id}/pet/{pet_id}', response_model=response_models.AggregatedReport, tags=["Report"])
Maybe we should also append `/aggregate` since there could be different types of reports

2024-04-26 19:07 UTC, fabieu commented on sureflap_api/models/response.py
> +
For a full list of avaialable fields take a look at the schema for ReportHouseholdResource at https://app-api.beta.surehub.io/index.html?urls.primaryName=V1.
I would like to include all fields for newly developed endpoints.

2024-06-26 15:52 UTC, closed without merging